README.md, pkgs/android-prepare-vendor/default.nix, release.nix
Built a vanilla image successfully, but untested since I don't have one.
=> Enable support for coral/flame (Pixel 4 (XL))

README.md
The default maximum ccache size is 5GB, which is not very useful when building Android. This adds a line to the ccache instructions to change the maximum size to 100GB.
=> README: add line to set ccache size

flavors/vanilla/default.nix
during build of marlin/sailfish, vendor build seeing a build id mismatch. This patch makes the build id compatible.
=> use same build id for marlin

flavors/vanilla/default.nix, flavors/vanilla/kernel-hashes.json, flavors/vanilla/kernel-metadata.json, flavors/vanilla/update-kernels.py, modules/kernel.nix, modules/pixel/default.nix
I'm currently only doing this for Android 11, and not Android 10, which isn't receiving security updates anyway.
This could likely be improved significantly--especially around the updater / metadata.  (e.g. we have to specify the tags in two places right now). 
I unfortunately can't directly test this on a real device since I use the kernels from GrapheneOS on my `crosshatch`, and those are already building fine.  I really ought to get another backup device to test things on...  I'd be interested if anyone trying out Robotnix currently on pixel phones could try this branch, to have some assurance I'm not breaking anything.  If not, I'll YOLO merge this anyway, since I'd rather have broken device images than vulnerable kernels.  If it breaks, you can always temporarily work around it by …
=> Build vanilla kernels from source

modules/apps/prebuilt.nix, modules/google.nix, modules/microg.nix, pkgs/build-tools/default.nix, pkgs/default.nix
This adds an APK signature verification derivation called `verifyApk`.  `verifyApk` takes an input APK file and certificate sha256, and outputs a symlink to that file if and only if the APK signature is valid and the certificate SHA256 digest matches the one provided.  The goal is to ensure _authenticity_ of build inputs in addition to _integrity_, which is already ensured via use of Nix.  
This is currently just being used for the prebuilt MicroG and Google APKs derived from a Google image. (We build everything else from source.)  These are example uses of `verifyApk`, and don't provide a ton of additional assurance, in contrast to if we fetched APKs from other (less trustworthy) sources. The Google APKs are currently directly from a Google image, whose SHA256 comes from the …
=> APK signature verification

apks/auditor/customized-auditor.patch, apks/auditor/default.nix, modules/apps/auditor.nix, nixos/attestation-server/customized-attestation-server.patch, nixos/attestation-server/default.nix, nixos/attestation-server/module.nix
I've added sunfish to the Auditor app and the Attestation server, ~however, I have to admit that I have not yet managed to make this work.  When I try to verify I receive “Scanned invalid account QR code” so I must have forgotten another spot where I have to add support for sunfish.~ EDIT: Turns out, I'm just a complete idiot and have overlooked that the app has actually been renamed to “Robotnix Auditor” and when using the correct app, attestation works flawlessly.
Also the modules now have assertions, because otherwise if your device is not supported it just silently fails to generate appropriate code.
---
BTW, you can disable registration on a public attestation instance using
```nix
{
services.nginx.virtualHosts."${config.services.attestation-server.domain}" = { …
```
=> Add sunfish to attestation

docs/attestation.md, docs/f-droid.md, docs/installation.md, docs/sunfish.md
These are just some notes I made during setting up my sunfish with GrapheneOS.
The file `sunfish.md` contains notes regarding the device (mostly all the power-volume-key combos that you have to press).
For some time I was quite clueless about where to find public keys for F-Droid repos, so I documented that in `f-droid.md`.
Finally my experiences setting up the attestation server are written down in `attestation.md`.
---
Instead of dumping everything into a `docs` folder in the main repo, we could also use the GitHub Wiki but to contribute on your GitHub Wiki I probably need push access which is not great.  The GitHub permission system is not exactly fine-grained.
=> Documentation

README.md, flavors/grapheneos/default.nix, modules/apps/auditor.nix, modules/apps/fdroid.nix, modules/apps/prebuilt.nix, modules/base.nix, modules/google.nix, modules/microg.nix, modules/release.nix, modules/signing.nix, modules/webview.nix, pkgs/default.nix, pkgs/robotnix/default.nix, release.nix
I've delayed pushing this breaking change to master until the next GrapheneOS release (likely today/tomorrow), so I can do a final test on my own personal device. Fixes part of the issues discussed in #24
We now use new application-specific keys and certificates for included apps
like Chromium / webview, Microg, and F-Droid, instead of relying on the
device-specific `releasekey`.  This allows us to share these keys between
multiple devices, push the same app updates to multiple devices, and remove an
ugly SELinux workaround for GrapheneOS that robotnix required.
Unfortunately, changing app keys will lose any data associated with those apps.
Fortunately, most data associated with those apps should be easy to re-create.
(Re-login to services in chromium, re-add F-Droid repos, etc.)
I hope …
=> signing: major change to use app keys by default

docs/attestation.md, nixos/attestation-server/module.nix
This adds email configuration to the attestation server.  Honestly, I have not really tried this out yet, because it only sends emails after a minimum interval of 32 hours without successful attestation.  Nevertheless, the attestation server starts up fine with this configuration and I see journal messages like
```
attestation-server.service AttestationServer[877]: dispatching alerts
```
without errors.  This PR also includes the trick to disable account creation and I've added a switch to enable ACME directly from the attestation server, so I don't need an extra block for nginx in my `configuration.nix`.
=> nixos/attestation-server: email configuration

pkgs/robotnix/default.nix
This should work even with stable nix (2.3.x).
=> sha256Fingerprint: don't use IFD

modules/apps/updater.nix
I needed to build another ROM to get OTA updates to work, because I didn't read the description and omitted the trailing slash.
Alternatively an `assert` could be used.
=> updater: enforce trailing slash requirement

.github/workflows/instantiate.yml, modules/apps/fdroid.nix, modules/apps/prebuilt.nix, modules/apv.nix, modules/signing.nix, pkgs/android-prepare-vendor/default.nix
While IFD is convenient, it has a number of downsides. I believe its use was the cause of recent CI failures.  This also makes evaluation much quicker.
This should remove any uses of IFD in the derivations checked in `release.nix`.
However, IFD is still to get the key/cert fingerprints used in user-signed builds.  This may be tackled at some point in the future.
---
_(edit: new theory for CI failure is that evaluation memory usage is too high)_
=> Remove "import from derivation" (IFD) from release.nix

modules/release.nix, nixos/attestation-server/module.nix
https://github.com/danielfullmer/robotnix/commit/5e6510b57b546a43e02e8c5d95511710c6f1759f broke `incrementalOta`. This fixes the evaluation error.
Further on my own server I have experienced some random startup errors of the attestation server similar to this:
```
install[1466]: /nix/store/z1qvlavy35wanw5k54fvvfffws5bvigj-coreutils-8.31/bin/install: invalid user ‘attestation-server’
systemd[1]: attestation-server.service: Control process exited, code=exited, status=1/FAILURE
```
I guess that systemd sets up the dynamic user lazily, i.e. when the first command runs as root the dynamic user doesn't exist yet.  Hence I just added another command before that and haven't had any startup errors since.
=> Fix evaluation error for incrementalOta

flavors/lineageos/default.nix, modules/release.nix, modules/signing.nix
Added the `--backup=true` option for `ota_from_target_files` used by LineageOS.  This should enable running `backuptool.sh` upon OTA updates, which should then run scripts in `/system/addons.d`.
See also: https://wiki.lineageos.org/signing_builds.html
Fixes #62
CC @Atemu
=> LineageOS OTA option fix

nixos/attestation-server/test.nix, release.nix
Adds a basic test of the attestation server, which currently just ensures it starts correctly.  This test currently fails due to https://github.com/danielfullmer/robotnix/issues/80.  It does work, however, if the email configuration is not set.
If/when we have the cuttlefish virtual device working well with NixOS tests, it might be possible told do a more complete end-to-and test!
Tested using `nix-build ./release.nix -A tests.attestation-server`
CC @hmenke
=> attestation-server: add basic nixos test

nixos/attestation-server/module.nix, nixos/attestation-server/test.nix
=> Avoid race condition in attestation-server

.github/workflows/instantiate.yml, nixos/attestation-server/test.nix, release.nix
Currently this takes about 5 mins to complete.  Maybe this should be pushed to cachix so that the test is only run when something actually changes and just substituted otherwise?
=> run nixos tests in github CI

pkgs/default.nix
The addition of flake support comes at a convenient time for me.  I'm just in the process of migrating all my systems to flakes.  Unfortunately, the first draft broke the regular evaluation.  This fixes it by re-adding `pkgs/default.nix` and loading the locked revision from the `flake.lock` file.
=> flakes: use locked nixpkgs

flavors/vanilla/default.nix, modules/pixel/default.nix, release.nix
Uploading this here in case anyone has a Pixel 5 and would like to test. Upstream `android-prepare-vendor` support is nearly done.  
Pixel 4a (5g) support is reportedly similar. https://github.com/danielfullmer/robotnix/issues/52
I still need to build the kernel from source, as it currently just uses the prebuilt kernel.
Tested building with:
```
nix-build --arg configuration '{device="redfin"; flavor="vanilla";}' -A img
```
=> Pixel 5 (redfin) / Pixel 4a (5g) (bramble) support

NEWS.md, docs/src/building.md, example.nix, modules/apps/prebuilt.nix, modules/release.nix, modules/signing.nix, template/flake.nix
Renames `keyStorePath` to `signing.keyStorePath`. Also introduces a `signing.buildTimeKeyStorePath` option, which is useful if we can't use the Nix sandbox to bind-mount our keys under `/keys`.
If you use the Nix sandbox normally, there's no need to use `signing.buildTimeKeyStorePath`, since using it makes the signing derivations contain a string of the path your keys are located  under.
(I needed `signing.buildTimeKeyStorePath` so I could produce a derivation which would sign the build with snakeoil keys under `/nix/store`.)
Closes #41
=> Keys refactor again

flavors/grapheneos/default.nix, modules/apps/seedvault.nix
Submitting as a PR in case there are any comments about this way of handling packages which could be included by either the upstream flavor or by a robotnix module.
---
Previously, we have stripped out upstream versions of packages if we
have a corresponding robotnix module which has the same functionality.
To better match upstream builds for reproducibility, we should not do
this _unless_ the upstream package is a prebuilt APK that we want to
build ourselves.
Since Seedvault (as of Android 11) can be built inside AOSP, and does
not have to be included as a prebuilt APK, we can use the flavor's
version instead, if it exists.
We introduce an internal option called apps.seedvault.includedInFlavor,
which is meant to be set by the flavor, and indicates that Seedvault
would be included …
=> seedvault: add includedInFlavor option

.github/workflows/instantiate.yml, modules/source.nix, tests/eval.nix
Includes first pure-evaluation test using the `runTests` from `nixpkgs`.
=> Pre-populate mount points if necessary

default.nix, docs/src/modules/flavors.md, flavors/anbox/default.nix, flavors/anbox/repo-anbox.json, flavors/anbox/repo-pmanbox.json, flavors/anbox/update.sh, flavors/anbox/webview-hack.patch, modules/7/default.nix, modules/base.nix, release.nix
~~Hey, look at the time, it's yet another rushed/incomplete port o'clock!~~
~~Hopefully this one actually works fine for me, compared to the TWRP port.~~
After some more work, it works!
There are things I'm unsure about, look at the inline comments.
Some of the commits at the tip of this branch are expected to be lopped-off before merging :). Anything below `=====` markers in the git history is assumed to be complete AFAIK.
* * *
```nix
{ config, pkgs, lib, ... }:
{
device = "arm64";
flavor = "anbox";
}
```
=> Add support for anbox

apks/chromium/default.nix, modules/base.nix
This should not affect anyone not using remote builders. Without this, when using hydra or remote builders, these can get distributed to machines where the builds fail.
Maybe this should be documented.
=> require big parallel for big derivations

apks/chromium/mk-vendor-file.py, cachix-push.sh, docs/src/development.md, flake.nix, flavors/anbox/update.sh, flavors/grapheneos/extract-upstream-params.sh, flavors/grapheneos/update.sh, flavors/lineageos/update-device-dirs.py, flavors/lineageos/update-device-metadata.py, flavors/lineageos/update.sh, flavors/vanilla/update.sh, mk-repo-file.py, modules/pixel/update.sh, pkgs/fetchgit/builder.sh, pkgs/fetchgit/default.nix, pkgs/fetchgit/nix-prefetch-git, pkgs/fetchgit/nix-prefetch-git.nix, pkgs/overlay.nix, shell.nix
Removed `--mirror` args from `mk-repo-file.py`.  Now both `pkgs.fetchgit` and `mk-repo-file.py` will use `ROBOTNIX_GIT_MIRRORS` as a single source of this metadata.
I considered another alternative, which was to add a `mirrors` option to the robotnix config, and have `fetchgit` get this metadata from the `mirrors` option.  However, this makes reuse of robotnix configurations across machines only possible if they have the same local mirrors set up.
Instead, here, `fetchgit` gets `ROBOTNIX_GIT_MIRRORS` through `impureEnvVars`.  Since `fetchgit` derivations are all fixed-output, it should not change any derivation hashes to add this functionality.
---
From docs:
Robotnix can be configured to use local git mirrors of Android source code. The AOSP documentation includes instructions to [create …
=> Add ROBOTNIX_GIT_MIRRORS environment variable

docs/src/building.md, docs/src/installation.md
I recently went through the process of building GrapheneOS using Robotnix and installing it on a Pixel 4a and made some improvements to the documentation based on that experience.
I have put my changes into separate commits, because I thought you might want to have some but not all of them.
=> Small docs fixes based on a Pixel 4a GrapheneOS install experience

flavors/vanilla/default.nix, modules/apps/prebuilt.nix
This allows the user to change or remove the prefix added to the module name, making the resulting image look cleaner. The user is responsible for making sure that the prefix they choose doesn't cause conflicts.
Also stick in another tiny patch to PRODUCT_BRAND to match the official images.
=> modules/apps/prebuilt: Allow configuring the module name prefix

flavors/grapheneos/repo-SP1A.210812.015.2021112021.json, flavors/grapheneos/repo-SP1A.211105.002.2021112021.json, flavors/grapheneos/repo-SP1A.211105.003.2021112021.json, flavors/grapheneos/repo-SP1A.211105.004.2021112021.json, flavors/grapheneos/upstream-params.nix
Tested on bramble.
Does _not_ include the vanadium update.
=> grapheneos: 2021111414 -> 2021112021

flavors/vanilla/12/default.nix
ProtonAOSP released their alpha builds for Pixel 6 (Pro), along with their implementation of UdfpsHbmprovider.
=> raviole: Add fingerprint patches from ProtonAOSP

modules/release.nix
=> release/otaMetadata: fix dependency on signedTargetFiles when building LineageOS releaseScript

default.nix, modules/release.nix
This is useful for devices that have a dedicated recovery image. This
includes, but is not limited to old devices, and *newest* devices. This
is because newest devices with dynamic partitions has dropped the silly
"boot as recovery" scheme, and rely again on a discrete recovery
partition.
This is useful mainly for LineageOS like deployment schemes.
Tested only with LineageOS devices, tested with:
- :heavy_check_mark: begonia\*
- :heavy_check_mark: lavender
Counter-tested with boot-as-recovery devices on LineageOS:
- :x: aura
- :x: pioneer
This fails (as expected) with those devices as they don't have a recovery partition.
Side-note: only the *lavender* recovery image was tested on-device this way. *begonia* is a mess for many reasons, and I haven't dared try the LineageOS recovery on it. …
=> Provide recoveryImg output

flavors/vanilla/12/default.nix, flavors/vanilla/12/repo-android-12.0.0_r27.json, modules/apv/latest-telephony-provider.json, modules/pixel/pixel-beta-imgs.json, modules/pixel/pixel-drivers.json, modules/pixel/pixel-imgs.json, modules/pixel/pixel-otas.json
The January update for the Pixel 6 (Pro) is finally here. Tested to boot on my Pixel 6.
Following the disastrous December patch, we will have to see how Google will manage to mess it up again this time :stuck_out_tongue:
=> vanilla/raviole: SQ1D.211205.017 -> SQ1D.220105.007

flavors/lineageos/default.nix, flavors/lineageos/lineage-19.0/device-dirs.json, flavors/lineageos/lineage-19.0/repo.json, flavors/lineageos/lineage-19.0/vendor-dirs.json
Initial support for building LineageOS 19.0.
Has been tested to boot correctly according to @danielfullmer.
=> lineageos: 19.0 init

flavors/vanilla/12/default.nix
Currently on the Pixel 6 (Pro), the "Battery usage" screen only shows information on the last chunk (~20 minutes). These patches from AOSP master fix the problem and enable the full history to be shown.
Tested with the Pixel 6.
=> raviole: Add patches for battery history graph

scripts/mk_repo_file.py
Got impatient waiting for the 12.1 tags to sync. I didn't time the before/after runs but verified that it was indeed parallelized.
Fixes #169.
=> mk_repo_file: Parallelize fetch

.github/workflows/grapheneos-update.yml, flavors/grapheneos/extract-upstream-params.sh
Big thanks to @Kranzes for prior work!
You can see an example of this in action here:
- Action run: https://github.com/hmenke/robotnix/runs/6038224236
- Resulting PR: https://github.com/hmenke/robotnix/pull/1
The latest GrapheneOS update was pretty small. I don't know whether this workflow will still perform with larger updates or if it runs into memory limits just like the LineageOS update workflow.
This workflow breaks if GrapheneOS pushes out an update for only one device family, e.g. https://grapheneos.org/releases#2022031103, but that rarely happens and is also not supported by the rest of robotnix.
Another failure will occur when the release identifier changes, e.g. `S2B3.220205.007.A1 -> SP2A.220305.013.A3`. I have no idea how to postdict these identifiers, i.e. how do I know that …
=> workflows: Add workflow to automatically update GrapheneOS

default.nix, modules/security-pki.nix
I use a custom CA for my internal systems, including the machine that serves my robotnix updates.  Although Android allows users to add CA certs, these don't appear to affect system services such as the updater.  This patch adds an option, "security.pki.certificateFiles" (named after the one in NixOS) which allows the user to add a list of CA certs at the system level.  I have tested that this works with the built-in updater app on GrapheneOS.
=> Add security.pki.certificateFiles option

modules/microg.nix
This PR obsoletes https://github.com/danielfullmer/robotnix/pull/198
The main feature that is added by this upgrade to microg is the ability to use FIDO2 security keys via USB or NFC
=> microg: 0.2.24.214816 -> 0.2.26.223616

flake.nix
'go-pup' has been renamed to/replaced by 'pup'
=> Fix devshell

flavors/vanilla/12/default.nix
When I try to build the current master branch with a minimal config like
```
{
inputs.robotnix.url = "github:danielfullmer/robotnix";
outputs = { self, robotnix }: {
robotnixConfigurations."dailydriver" = robotnix.lib.robotnixSystem ({ config, pkgs, ... }: {
device = "oriole";
flavor = "vanilla"; # "grapheneos" is another option
apps.chromium.enable = false;
});
defaultPackage.x86_64-linux = self.robotnixConfigurations."dailydriver".img;
};
}
```
I get a hash mismatch on a fixed output derivation
```
error: hash mismatch in fixed-output derivation '/nix/store/vp7qgg4s87xvwhxc11kq05y84m37dmi5-include-saved-battery-history-chunks-into-batteryusagestats-parcel.patch.drv':
specified: sha256-ZIi96yF2qTgQ4iGTY86ppBmg4TeIRJ1qu7CSA5IPSnE=
got: …
```
=> hash mismatch in fixed-output derivation - include-saved-battery-history-chunks-into-batteryusagestats-parcel

flavors/lineageos/update_device_metadata.py
https://github.com/LineageOS/hudson now uses main instead of master branch, changed about 4 months ago.
=> lineageos: change hudson metadata branch from master to main

flake.lock, flake.nix, modules/base.nix, modules/envpackages.nix, pkgs/default.nix, pkgs/overlay.nix
This commit bumps nixpkgs to 23.11, while incorporating small changes to ensure everything works.
At the same time, nixpkgsUnstable has been removed as it does not seem to be needed anymore.
android-nixpkgs has been bumped to the latest version as well.
`LD_LIBRARY_PATH` paths has been added to buildFHSUSerEnv, because of upstream changes. Please see the following information if curious.
https://github.com/NixOS/nixpkgs/issues/103648
https://github.com/NixOS/nixpkgs/issues/112266
https://github.com/NixOS/nixpkgs/issues/262775
https://github.com/NixOS/nixpkgs/pull/263201
https://github.com/NixOS/nixpkgs/pull/278361
Successfully build image for FP4 using flavor LineageOS. Haven't flashed image however.
Unsure if robotnix should target nixos-unstable, instead of nixos-23.11. But this can …
=> Bump nixpkgs to 23.11, android-nixpkgs to latest and remove nixpkgsUnstable

modules/apps/fdroid.nix
Old versions of f-droid are frequently pushed out of the active repo into the archive which would make the build fail a few months in the future.
The `urls` attribute of `fetchurl` makes it try those URLs in order.
=> fdroid: use archive as fallback

modules/microg.nix
Also refactored the version declaration now that GmsCore and FakeStore are in the same repo. This is now a lot simpler to update and doesn't require knowledge/explanations about how to split the parts.
=> microg: v0.2.29.233013 -> v0.3.3.240913

modules/signing.nix
The build of generate_verity_key because openssl/rsa.h header could not be found, fix the issue by pointing into boringssl.dev package.
=> generateKeysScript: Fix build of android-key-tools

modules/signing.nix
Makes the signing script work again with Android 13. Tested with lineage-20.0 build
=> Add support for signing target files in Android 13

modules/signing.nix
Depends on https://github.com/nix-community/robotnix/pull/259
Makes the signing script work again with Android 13. Tested with yet unmerged lineage-21.0 build. Also tested signing scripts work for Android 13 (especially the APEX part), although I didn't test flashing that image
=> Add support for signing target files in Android 14

scripts/robotnix_common.py
As the title says. Previously, the script assumed that the path was not absolute and errored out because of this.
=> Handle the NIX_REMOTE=daemon case in `get_store_path`

flavors/lineageos/default.nix, modules/webview.nix
We don't have a working webview which would mean you'd need to install one
yourself at runtime. LOS ships a prebuilt webview, let's simply use that.
Fixes https://github.com/nix-community/robotnix/issues/246
=> lineageos: allow prebuilt webview

flavors/lineageos/update.sh
From a discussion we had on the matrix channel. This adds a `-s` option to skip `mk_repo_file.py` in the lineageos `update.sh` script.
What are the condition to met to use this option ? I'd like to document when it is useful.
=> lineageos: add option to skip mk_repo_file.py in update.sh

flake.lock, flake.nix, pkgs/fetchgit/builder.sh, pkgs/fetchgit/default.nix, pkgs/fetchgit/nix-prefetch-git, pkgs/gitRepo/default.nix, pkgs/gitRepo/ignore_dubious_ownership.patch, pkgs/overlay.nix
It built fine but I'll have to test on a real device.
=> flake: bump to 2024
