nix-community/robotnix

flavors/lineageos/update-devices.py
Baby's first Python, feedback welcome
=> Make update-devices.py incremental 

flavors/lineageos/default.nix, flavors/lineageos/update-devices.py, flavors/lineageos/vendor-dirs.json
=> Bacon quirk workaround

modules/microg-android11.patch, modules/microg.nix
Tested in emulator: self-check, device registration, push notifications
CC @petabyteboy
=> microg: Add patch for Android 11

modules/microg.nix
=> microg: 0.2.12.203315 -> 0.2.13.203915

apks/chromium/vanadium.nix, flavors/grapheneos/default.nix, flavors/grapheneos/repo-RP1A.201105.002.2020.11.27.15.json
Flashed and booted on sunfish.  Everything still seems to work.
=> grapheneos: 2020.11.25.22 -> 2020.11.27.15

flavors/lineageos/default.nix, flavors/lineageos/device-dirs.json, flavors/lineageos/device-metadata.json, flavors/lineageos/repo-lineage-17.1.json, flavors/lineageos/vendor-dirs.json
Excludes upstream's Flox inclusion because of https://github.com/danielfullmer/robotnix/issues/76
=> lineageos: 2020-12-29 update

example.nix, template/flake.nix
=> Fix gotchas in examples

docs/src/modules/flavors.md
=> Fix spelling

default.nix, lib/default.nix, modules/pixel/active-edge.nix
I miss being able to squeeze to take a screenshot. Tested on a Pixel 3 with the vanilla flavor.
=> Add Active Edge support for Pixel devices

modules/pixel/active-edge.nix
=> pixel/active-edge: Add support for Android 12

modules/apps/chromium.nix, modules/apps/prebuilt.nix
Building `generateKeysScript` with a simple configuration of:
{device="crosshatch"; flavor="vanilla"; signing.enable=true; }
would result in Nix trying to import the key fingerprint for chromium.
This is shouldn't happen because the generateKeysScript should have no
data dependency on the actual APK that would be built.
The chain of dependencies was generateKeysScript -> keyTools ->
config.source.dirs -> nonNullPrebuilts (in modules/apps/prebuilts).
This nonNullPrebuilts would have to further evaluate the apk to decide
if it was null, which would ultimately pull depend on things further
down the chain (such as the IFD step to get the cert fingerprint).
Fixed by simply adding a apps.prebuilt.enable option, which defaults to
true if the apps.prebuilt.\<name\> submodule is set.
Closes #135 …
=> Fix improper dependency of generateKeysScript on keyStorePath

flavors/grapheneos/repo-SP1A.210812.015.2021112404.json, flavors/grapheneos/repo-SP1A.211105.002.2021112404.json, flavors/grapheneos/repo-SP1A.211105.003.2021112404.json, flavors/grapheneos/repo-SP1A.211105.004.2021112404.json, flavors/grapheneos/upstream-params.nix
=> grapheneos: 2021112021 -> 2021112404

flavors/lineageos/default.nix, flavors/lineageos/device-metadata.json, flavors/lineageos/lineage-17.1/device-dirs.json, flavors/lineageos/lineage-17.1/repo.json, flavors/lineageos/lineage-17.1/vendor-dirs.json, flavors/lineageos/lineage-18.1/device-dirs.json, flavors/lineageos/lineage-18.1/repo.json, flavors/lineageos/lineage-18.1/vendor-dirs.json
~~Waiting on builds to finish.~~
=> lineageos: 2021102406 -> 2022010122

flavors/lineageos/default.nix, flavors/lineageos/lineage-17.1/device-dirs.json, flavors/lineageos/lineage-17.1/repo.json, flavors/lineageos/lineage-17.1/vendor-dirs.json, flavors/lineageos/lineage-18.1/device-dirs.json, flavors/lineageos/lineage-18.1/repo.json, flavors/lineageos/lineage-18.1/vendor-dirs.json
Huh...
Don't expect frequent updates from me, I said.
But as I was winding down, I saw that the LineageOS maintainer for aura fixed the main issues, and I wanted to confirm.
So here: a fresh update!
Tested on:
=> lineageos: 2022010122 -> 2022010904

flavors/lineageos/0001-Remove-LineageOS-keys-12.patch, flavors/lineageos/default.nix, flavors/lineageos/lineage-17.1/repo.json, flavors/lineageos/lineage-18.1/device-dirs.json, flavors/lineageos/lineage-18.1/repo.json, flavors/lineageos/lineage-19.1/device-dirs.json, flavors/lineageos/lineage-19.1/repo.json, flavors/lineageos/lineage-19.1/vendor-dirs.json
Updating the other branches wasn't strictly necessary and was done for
consistency
~~Still need to rebase one of the patches for this to work.~~
=> lineageos: 19.0 -> 19.1; 2022031908 -> 2022032118

flavors/lineageos/update.sh
You likely need to set buildDateTime after updating
=> lineageos/update: print timestamp on completion

flavors/grapheneos/repo-SP1A.210812.016.C1.2022041300.json, flavors/grapheneos/repo-SP2A.220405.003.2022041300.json, flavors/grapheneos/repo-SP2A.220405.004.2022041300.json, flavors/grapheneos/upstream-params.nix
=> grapheneos: 2022041100 -> 2022041300

apks/chromium/buildenv.nix, apks/chromium/default.nix, modules/base.nix, modules/envpackages.nix, modules/release.nix, modules/source.nix, pkgs/android-emulator/default.nix, pkgs/android-prepare-vendor/default.nix
Otherwise it will not eval with `nixpkgs.config.allowAliases = false;`
=> Do not use package aliases

modules/base.nix
Follow up on #230 , adds `-u` as well.
=> even stricter build phases (unset variables)

README.md
Wanted to document the current status in order not to mislead people discovering this project.
@eyJhb are you fine with being listed here like this?
Anyone else who has experience and still lurks in this repo should feel free to add themselves if they want to offer to share their knowledge on specific components.
=> README: document project status

default.nix
Fixes https://github.com/nix-community/robotnix/issues/273
=> expose finalPkgs directly

docs/src/modules/flavors.md, flavors/lineageos/device-metadata.json, flavors/lineageos/lineage-21.0/device-dirs.json, flavors/lineageos/lineage-21.0/vendor-dirs.json, flavors/lineageos/lineage-22.1/device-dirs.json, flavors/lineageos/lineage-22.1/vendor-dirs.json, flavors/lineageos/supported_devices.toml
This adds FP3 device, and update lineage os device metadata for 21 and 22.
=> lineageos: add FP3 device
